### ISSUE TITLE
Split Payment tendo eu como recebedor junto com o lojista

### ISSUE THREAD

**Issue by davidrock** [pagarme/pagarme-net#103]
Olá, estou desenvolvendo num marketplace e preciso desenvolver o Split Payment onde EU, o dono do sistema, receberei uma porcentagem x de cada compra realizada. Na documentação só encontrei informação sobre como dividir a conta com mais de um lojista, o que não é o meu caso. Por exemplo, quero que quando o usuário fizer uma compra de um produto que custou R$10, o vendedor receba R$9 e eu receba R$1, como se fosse uma comissão! Com esse R$1 indo pro meu saldo da Pagarme.

Tem como fazer isso?

**Comment by jonatasmaxi** [comment]
Olá @davidrock é possível atribuir uma porcentagem específica ao recebedor principal sim a outra parte da transação também precisa ser um recebedor do pagar.me para que a divisão aconteça. Faz sentido?

**Comment by davidrock** [comment]
@jonatasmaxi então eu preciso mesmo criar um recebedor para mim mesmo?

**Comment by murilohns** [comment]
fala @davidrock , não precisa criar um recebedor pra sua conta não! Por padrão, ela já tem um, atrelada aos dados bancários cadastrados na [dashboard](https://dashboard.pagar.me).

Pra pegar o ID do recebedor principal, você pode acessar [essa rota](https://api.pagar.me/1/company?api_key=SUA_CHAVE_DE_API)

e procurar pelo campo `default_recipient_id`. Basta pegar o ID de acordo com o ambiente de sua chave de api (test ou live)

**Comment by lucazin** [comment]
Pessoal, estou com essa mesma dúvida em como pefar o default recipient id mas na API .Net
