### ISSUE TITLE
Exemplo de código Settando Metadata (tipo AbstractModel)

### ISSUE THREAD

**Issue by vfilenga** [pagarme/pagarme-net#105]
Sei que não se trata exatamente de uma issue, mas como não existe mais a funcionalidade de mensagem privada para usuários no github e todos os exemplos de código da api docs estão com o parametro metadata nullado, gostaria de pedir que alguém me mostrasse programaticamente como criar uma instancia desta classe para salvar na pagar.me as informações adicinais de uma assinatura que digam respeito ao contexto do sistema integrador.

**Comment by jonatasmaxi** [comment]
Olá @vfilenga segue o exemplo da criação de assinatura com Metadata, qualquer dúvida permaneço à disposição.

**Comment by vfilenga** [comment]
Perfeito @jonatasmaxi
