### ISSUE TITLE
Suporte para o .NET CORE ?

### ISSUE THREAD

**Issue by srburton** [pagarme/pagarme-net#110]

**Comment by EduardoPires** [comment]
Fiz um port bem rápido, veja se está te atendendo:
https://github.com/EduardoPires/pagarme-net

**Comment by srburton** [comment]
Show, valeu depois vou dar  uma olhada.

**Comment by carloscfcortez** [comment]
@EduardoPires  tomei a liberdade de subir o package já que o pessoal da Pagar.me não atualizaram
https://www.nuget.org/packages/PagarMeCore/1.0.0#
