### ISSUE TITLE
Erro nos campos tid e nsu no retorno de transações

### ISSUE THREAD

**Issue by cloviscoli** [pagarme/pagarme-net#17]
Os campos **tid** e **nsu** do objeto **Transaction** segundo a documentação da Pagar.me são do tipo String [https://docs.pagar.me/api/#objeto-transaction](url) e na Classe **Transaction** dentro do projeto Shared [https://github.com/pagarme/pagarme-net/blob/master/PagarMe.Shared/Transaction.cs](url) esta retornando **Int**, isso está causando um erro na hora de pegar os dados da transação quando é retornado da Pagar.me.

**Comment by thufik** [comment]
Bom dia Clovis,

Os campos tid e nsu retornam um inteiro realmente, a documentação estava equivocada nessa ponto, já corrigimos na nova versão que será lançada em breve. De qualquer forma, obrigado.

**Comment by murilohns** [comment]
corrigido através do #63
