### ISSUE TITLE
Estorno de pagamento via boleto bancário

### ISSUE THREAD

**Issue by danilocardia** [pagarme/pagarme-net#29]
Olá,

Estou implementando a funcionalidade de estorno de transações. Para as transações pagar com cartão de crédito está funcionando corretamente porém no caso de boleto bancário, onde devo informar os dados da conta para depósito, estou recebendo a mensagem de erro que os dados bancários (bank_account) não estão sendo passados.

Na documentação não consta essa informação para C# e eu já tentei passá-los de várias formas.

Vocês poderiam me passar um exemplo em C# de estorno para boleto bancário?

Obrigado.

**Comment by rodrigoPgSup** [comment]
Boa tarde Danilo, como vai meu caro? 

Estamos trabalhando para corrigir essa questão, e quanto antes faremos atualização em produção. Muito obrigado pela observação Danilo.

Att.

**Comment by rodrigoPgSup** [comment]
Olá @danilocardia , como vai meu caro? 

Fizemos a atualização, você só precisa agora atualizar o package. Muito obrigado pela observação.

Att.

**Comment by danilocardia** [comment]
Olá @rodrigoPgSup, atualizei o package porém agora estou com uma dúvida.

Não é possível fazer estorno parcial caso o pagamento tenha sido boleto bancário?

A única forma de fazer seria utilizando um dos dois overloads do método Refund?
![image](https://cloud.githubusercontent.com/assets/7659897/20492478/0dd93126-affc-11e6-916e-8399d0d0b3dc.png)

Obrigado.
