### ISSUE TITLE
Parâmetro ausente (boleto_instructions)

### ISSUE THREAD

**Issue by daraujo3** [pagarme/pagarme-net#49]
boleto_instructions não consta no o objeto de "Transaction"

default: null
Campo instruções do boleto. Máximo de 255 caracteres

**Comment by sinctec** [comment]
+Up
Alguma previsão para implementar?

**Comment by murilohns** [comment]
Olá @sinctec e @daraujo3, 

Resolvido através do PR #61. Basta atualizar a SDK

Att.
