### ISSUE TITLE
Erro ao criar novo cliente

### ISSUE THREAD

**Issue by enviou** [pagarme/pagarme-net#56]
Esta com erro para criar novo cliente, o campo external_id agora é obrigatário.

**Comment by leonardo-barbosa** [comment]
Olá @enviou, Tudo bem?
Meu nome é Leonardo, faço parte da equipe de Suporte Técnico do Pagar.me.

Referente à versão 2017-08-28 da nossa API, a mesma que possuí o campo external_id como obrigatório, a biblioteca de .net ainda não é compatível com a mesma, sendo assim ainda não pode ser utilizada para fazer a integração com o Pagar.me.

As únicas bibliotecas compatíveis atualmente são JS e Python.

Qualquer dúvida, estou à disposição.
