### ISSUE TITLE
Erro ao criar transação do tipo cartão de crédito (campo Billing)

### ISSUE THREAD

**Issue by jeanmallet** [pagarme/pagarme-net#60]
Prezados, 
Estou recebendo uma exceção ao tentar salvar uma transação utilizando a biblioteca. O erro informa que o parâmetro "billing" não foi informado (erro de validação). Entretanto, não encontrei na biblioteca (objeto Transaction) nenhum campo para preenchimento desses dados, assim como os "itens do pedido" (campos obrigatórios quando o anti-fraude está ligado). 

Como devo proceder para conseguir realizar a transação (cartão de crédito)?

Obrigado.

**Comment by murilohns** [comment]
Olá @jeanmallet, esse erro ocorre pois este SDK ainda não é compatível com a versão 2017-08-28 da API Pagar.me. Por enquanto, devo pedir que você envie um e-mail para relacionamento@pagar.me solicitando a alteração de sua chave para 2017-07-17.

Se eu puder ajudar em mais algo fico à disposição.

**Comment by murilohns** [comment]
Olá @jeanmallet, tudo bem?

Atualizamos a SDK para que seja possível enviar os campos necessários na versão 2018-08-28. Agora os campos `Billing`, `Shipping` e `Items` foram habilitados, além dos campos extras necessários para o `Customer`.

Se precisar de ajuda em mais algo fico à disposição :)
