### ISSUE TITLE
Suporte a paginação no retorno de collections de planos e assinaturas

### ISSUE THREAD

**Issue by rafaelgpo** [pagarme/pagarme-net#68]
Permitir paginação (count, page) em métodos que retornam collections de planos, assinaturas e outros
Atualmente os endpoints (Ex: GET /pans e /subscriptions ) possuem esse recurso, mas por padrão, retornam  apenas os 10 primeiros registros. Desta forma, os métodos do componente pagarme-net, sempre retornam os 10 primeiros e não dispõe da opção de paginar.

**Comment by murilohns** [comment]
Olá @rafaelgpo, tudo bem?

Acredito que você possa utilizar _tuple_ para fazer isso, ficaria algo parecido com isso:

```cs
var pagarmeRequest = PagarMeService.GetDefaultService().Subscriptions.BuildFindQuery(new Subscription());
var count = Tuple.Create("count", "1000");
var page = Tuple.Create("page", "10");

pagarmeRequest.Query.Add(count);
pagarmeRequest.Query.Add(page);

var subscriptions = PagarMeService.GetDefaultService().Subscriptions.FinishFindQuery(pagarmeRequest.Execute());
```

**Comment by murilohns** [comment]
olá @rafaelgpo, o código acima resolve seu problema?

**Comment by murilohns** [comment]
@rafaelgpo, estarei fechando essa issue, mas sinta-se a vontade para reabri-lá caso necessário.
