### ISSUE TITLE
Modo teste

### ISSUE THREAD

**Issue by lucazin** [pagarme/pagarme-net#96]
No api de modo teste, esta aceitando qualquer cartao ? mesmo que seja invalido ?
Passei um qualquer aqui e foi..  na hora que é feita a transacao é validado isso ?

**Comment by murilohns** [comment]
Olá @lucazin , no ambiente de testes nenhum cartão é validado, apenas seu BIN.

Então você pode usar o cartão `4111 1111 1111 1111` para simular transações de cartão de crédito em teste =)

**Comment by lucazin** [comment]
Ah muito bom !
Obrigado Murilo.

Deixa eu fazer uma pergunta

Consigo implementar uma transacao de cartao de credito com split em c#?

Se sim.. por exemplo 100 reais.. ai coloco minha taca de 5 %...

105 reais..  ..ai consigo dividit direto na conta bancaria.. 5 na minha e
100 na do meu lojista..?

Mas a duvida msm..sao aa taxas do pagarme... consigo via api definir quek
vai arcar com as taxas ? Como ?

Obrigado!

Em Qua, 25 de jul de 2018 15:42, Murilo Henrique Nascimento Souza <
notifications@github.com> escreveu:

**Comment by murilohns** [comment]
Olá @lucazin , tudo bem?

Sim, você consegue dividir uma transação com essa SDK, você pode ler mais sobre isso [nesse link](https://docs.pagar.me/docs/split-rules#section-criando-uma-transa%C3%A7%C3%A3o-com-split).

Sobre a divisão de taxas, existem alguns parâmetros no objeto SplitRule que definem quem será responsável por qual taxa:

charge_processing_fee: Indica se o recebedor vinculado à regra será cobrado pelas taxas da transação.

liable: Indica se o recebedor atrelado assumirá os riscos de chargeback da transação

charge_remainder: no caso de restos de divisão de taxas entre os dois recebedores exista, aquele com esse parâmetro 'true' será cobrado desses centavos

Tudo isso você pode encontrar [aqui](https://docs.pagar.me/docs/split-rules#section-par%C3%A2metros-de-uma-split-rule)
