### ISSUE TITLE
Conta Bancaria e Recebedor

### ISSUE THREAD

**Issue by lucazin** [pagarme/pagarme-net#97]
Bom dia!

Tem como apagar uma conta bancaria ou modificar ? 
contudo também tem como apagar um recebedor ?

Infelizmente criei alguns recebedores na api de testes e nao consigo apagar.

**Comment by murilohns** [comment]
Mesmo problema retratado nessa issue: https://github.com/pagarme/pagarme-js/issues/131

Estou fechando essa issue.
