### ISSUE TITLE
Transacao Split Rules

### ISSUE THREAD

**Issue by lucazin** [pagarme/pagarme-net#99]
Mesmo atribuindo na transacao o codigo abaixo 

 transaction.SplitRules = new[]
                     {
                         new SplitRule
                        {
                             Recipient = RecebedorID,
                             Percentage = 97,
                             ChargeProcessingFee = true,
                             Liable = true
                        },
                       new SplitRule
                       {
                             Recipient = Principal_ID,
                             Percentage = 3,
                             ChargeProcessingFee = false,
                             Liable = false
                       }
                    };

Ele me retorna a exceção " all split rules need a percentage property " quando aciona o transaction.save()

Estava funcionando normal, fui realizar um novo teste e recebi essa exception. 
Ontem estava tudo ok

O que pode ser?

**Comment by murilohns** [comment]
Fala @lucazin , tudo bem?

Estava tendo uma atualização no ambiente de testes da API, que acabou influenciando no comportamento de transações criadas com _SplitRule_.

Esse erro ocorreu apenas em ambiente de testes, e já foi corrigido, ok?

Abraços!

**Comment by lucazin** [comment]
Ah bacana, foi corrigido agora ? posso tentar novamente ?  Nem vou mexer no
meu codigo entao..

Em qua, 15 de ago de 2018 às 15:35, Murilo Henrique Nascimento Souza <
notifications@github.com> escreveu:

**Comment by lucazin** [comment]
Tudo certo! Obrigado mais 1 vez!

Em qua, 15 de ago de 2018 às 15:36, Lucas Bergamo <bergamo86@gmail.com>
escreveu:
